### ISSUE TITLE
DBus/MPRIS integration

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#11]
Integrate with MPRIS/DBus to publish what song is playing.

Work happening on the https://gitlab.com/robozman/libremsonic/tree/mpris-dbus-support branch.

# TODO:

- [x] Basic DBus Integration
- [x] Broadcast property changes
- [x] Implement `MediaPlayer2` interface
- [x] Implement `MediaPlayer2.Player` interface
- [x] Implement `MediaPlayer2.TrackList` interface
- [x] Implement `MediaPlayer2.Playlists` interface

**Comment by sumnerevans** [comment]
closed
